#!/usr/bin/env bash
# Install script for basicServerStatusGUI: check requirements, install deps, create wrapper binary.

set -e

# Project root = directory containing this script
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REQUIREMENTS="${PROJECT_DIR}/requirements.txt"
WRAPPER="${PROJECT_DIR}/basicServerStatusGUI"
MAIN_SCRIPT="${PROJECT_DIR}/basicServerStatusGUI.py"

echo "basicServerStatusGUI install"
echo "Project directory: ${PROJECT_DIR}"
echo ""

# Check Python 3
if ! command -v python3 &>/dev/null; then
    echo "Error: python3 not found. Please install Python 3."
    exit 1
fi
PYTHON="$(command -v python3)"
echo "Using Python: ${PYTHON} ($(python3 --version 2>&1))"

# Check requirements file
if [[ ! -f "${REQUIREMENTS}" ]]; then
    echo "Error: requirements.txt not found at ${REQUIREMENTS}"
    exit 1
fi
if [[ ! -f "${MAIN_SCRIPT}" ]]; then
    echo "Error: basicServerStatusGUI.py not found at ${MAIN_SCRIPT}"
    exit 1
fi

# Install requirements (prefer --user to avoid needing sudo)
echo ""
echo "Installing Python dependencies from requirements.txt..."
if python3 -c 'import sys; sys.exit(0 if hasattr(sys, "real_prefix") or (hasattr(sys, "base_prefix") and sys.base_prefix != sys.prefix) else 1)' 2>/dev/null; then
    python3 -m pip install -r "${REQUIREMENTS}"
else
    python3 -m pip install --user -r "${REQUIREMENTS}"
fi
echo "Dependencies installed."
echo ""

# Create wrapper binary: run the app from PROJECT_DIR so `import config` works
echo "Creating wrapper: ${WRAPPER}"
cat > "${WRAPPER}" << EOF
#!/usr/bin/env bash
# Wrapper generated by install.sh - runs basicServerStatusGUI from the project directory.
PROJECT_DIR="${PROJECT_DIR}"
exec python3 "\${PROJECT_DIR}/basicServerStatusGUI.py" "\$@"
EOF
chmod +x "${WRAPPER}"
echo "Wrapper created and made executable."
echo ""

# Optional: offer to add to user PATH via ~/.local/bin
if [[ -d "${HOME}/.local/bin" ]]; then
    if [[ "$(readlink -f "${WRAPPER}" 2>/dev/null)" != "$(readlink -f "${HOME}/.local/bin/basicServerStatusGUI" 2>/dev/null)" ]]; then
        echo "To run 'basicServerStatusGUI' from anywhere, add a symlink:"
        echo "  ln -sf '${WRAPPER}' '${HOME}/.local/bin/basicServerStatusGUI'"
        echo "(Ensure ~/.local/bin is in your PATH.)"
    fi
else
    echo "Run the app with: ${WRAPPER}"
    echo "Or add PROJECT_DIR to your PATH: export PATH=\"\${PATH}:${PROJECT_DIR}\""
fi
echo ""
echo "Done."
